services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coaster_system_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "9000:9000"
    depends_on:
      - redis

  webserver:
    image: nginx:latest
    container_name: coaster_system_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
    depends_on:
      - app
    restart: always

  redis:
    image: redis:latest
    container_name: coaster_system_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1"]
    restart: always

volumes:
  redis_data:
